<?php
include_once 'shop.php';
$shop = new Shop;
$productList = $shop->getProductList();
$product1 = $productList->addProduct('Продукт №1', 8);
$product2 = $productList->addProduct('Продукт №2', 10);
$courierList =  $shop->getCourierList();
$courierList->addCourier('Александр', 'Иванов', '+79514632468', 'ghdfd@dfsg.ru', 'Москва', 1, 0);
$courierList->addCourier('Иван', 'Петров', '+78544521496', 'fdgdf@dfhfd.ru', 'Москва', 0, 1);
$customerList =  $shop->getCustomerList();
$customerList->addCustomer('Алексей', 'Сидоров', '+78435687465', 'sdf@dsfd.ru', 'Москва', 0);
$customerList->addCustomer('Петр', 'Колесов', '+78514697865', 'dsfsd@sdvsd.ru', 'Москва', 1);
$basketList = $shop->getBasketList();
$customer =  $customerList->getCustomer(0);
$customerBasket = $basketList->getCustomerBasket($customer);
$customerBasket->addProduct($product1, 5);
$customerBasket->addProduct($product1, 5);
$customerBasket->addProduct($product2, 6);
echo "Остаток по первому продукту: " . $product1->getQuantity() . '</br>';
echo "Остаток по второму продукту: " . $product2->getQuantity() . '</br>';
echo 'Текущее состояние корзины:</br>';
var_dump($customerBasket);
echo '</br>';
$order = $shop->check($customerBasket);
echo 'Текущее состояние заказа:</br>';
var_dump($order);
echo '</br>';
echo 'Удаленные из корзины товары:</br>';
var_dump($customerBasket);
echo '</br>';
$deliveryList = $shop->getDeliveryList();
$delivery = $deliveryList->addDelivery($order, $courierList->getCourierList());
$delivery->setCourier();
echo "Товар готов к доставке.";
echo '</br>';
echo "Ваш курьер:";
var_dump($delivery->getCourier());
